/*
 RequireJS text 0.24.0 Copyright (c) 2010-2011, The Dojo Foundation All Rights Reserved.
 Available via the MIT or new BSD license.
 see: http://github.com/jrburke/requirejs for details
*/
(function(){var l=["Msxml2.XMLHTTP","Microsoft.XMLHTTP","Msxml2.XMLHTTP.4.0"],n=/^\s*<\?xml(\s)+version=[\'\"](\d)*.(\d)*[\'\"](\s)*\?>/im,o=/<body[^>]*>\s*([\s\S]+)\s*<\/body>/im,k=[];define(function(){var h,j,m;if(typeof window!=="undefined"&&window.navigator&&window.document)j=function(a,b){var c=h.createXhr();c.open("GET",a,true);c.onreadystatechange=function(){c.readyState===4&&b(c.responseText)};c.send(null)};else if(typeof process!=="undefined"&&process.versions&&process.versions.node){m=require.nodeRequire("fs");
j=function(a,b){b(m.readFileSync(a,"utf8"))}}else if(typeof Packages!=="undefined")j=function(a,b){var c=new java.io.File(a);a=java.lang.System.getProperty("line.separator");c=new java.io.BufferedReader(new java.io.InputStreamReader(new java.io.FileInputStream(c),"utf-8"));var e,d,f="";try{e=new java.lang.StringBuffer;if((d=c.readLine())&&d.length()&&d.charAt(0)===65279)d=d.substring(1);for(e.append(d);(d=c.readLine())!==null;){e.append(a);e.append(d)}f=String(e.toString())}finally{c.close()}b(f)};
return h={version:"0.24.0",strip:function(a){if(a){a=a.replace(n,"");var b=a.match(o);if(b)a=b[1]}else a="";return a},jsEscape:function(a){return a.replace(/(['\\])/g,"\\$1").replace(/[\f]/g,"\\f").replace(/[\b]/g,"\\b").replace(/[\n]/g,"\\n").replace(/[\t]/g,"\\t").replace(/[\r]/g,"\\r")},createXhr:function(){var a,b,c;if(typeof XMLHttpRequest!=="undefined")return new XMLHttpRequest;else for(b=0;b<3;b++){c=l[b];try{a=new ActiveXObject(c)}catch(e){}if(a){l=[c];break}}if(!a)throw new Error("require.getXhr(): XMLHttpRequest not available");
return a},get:j,load:function(a,b,c,e){var d=false,f=a.indexOf("."),p=a.substring(0,f),g=a.substring(f+1,a.length);f=g.indexOf("!");if(f!==-1){d=g.substring(f+1,g.length);d=d==="strip";g=g.substring(0,f)}b=b.nameToUrl(p,"."+g);h.get(b,function(i){i=d?h.strip(i):i;if(e.isBuild&&e.inlineText)k[a]=i;c(i)})},write:function(a,b,c){if(b in k){var e=h.jsEscape(k[b]);c("define('"+a+"!"+b+"', function () { return '"+e+"';});\n")}}}})})();
