(function(){/*
 MIT License (c) copyright B Cavalier & J Hann */
var h=!0,k=!1,l=this.window||global;function n(){}function p(a,b){return 0==aa.call(a).indexOf("[object "+b)}function q(a){return a&&"/"==a.charAt(a.length-1)?a.substr(0,a.length-1):a}function s(a,b){var c,e,d,f;c=1;e=a;b&&(e=e.replace(ba,function(a,b,e,d){e&&c++;f=h;return d||""}));if(f){d=b.split("/");if(c>d)throw Error("attempt to access module beyond root of package: "+a);d.splice(d.length-c,c);return d.concat(e||[]).join("/")}return e}
function ca(a){var b=a.indexOf("!");return{I:a.substr(b+1),i:0<=b&&a.substr(0,b)}}function t(){}function u(a,b){t.prototype=a||v;var c=new t;t.prototype=v;for(var e in b)c[e]=b[e];return c}
function w(){function a(a,b,d){e.push([a,b,d])}function b(a,b){for(var d,c=0;d=e[c++];)(d=d[a])&&d(b)}var c,e,d;c=this;e=[];d=function(f,c){a=f?function(a){a&&a(c)}:function(a,b){b&&b(c)};d=n;b(f?0:1,c);b=n;e=x};this.aa=function(b,e,d){a(b,e,d)};this.g=function(a){c.fa=a;d(h,a)};this.d=function(a){c.ea=a;d(k,a)};this.p=function(a){b(2,a)}}function z(a,b,c,e){a instanceof w?a.aa(b,c,e):b(a)}function A(a,b,c){var e;return function(){0<=--a&&b&&(e=b.apply(x,arguments));0==a&&c&&c(e);return e}}
function B(){function a(b,d,c,g){var i;i=C.f(D,x,[].concat(b));this.then=b=function(a,b){z(i,function(b){a&&a.apply(x,b)},function(a){if(b)b(a);else throw a;});return this};this.next=function(b,d,e){return new a(b,d,e,i)};d&&b(d,c);z(g,function(){C.h(i)})}var b=[].slice.call(arguments),c;p(b[0],"Object")&&(c=b.shift(),D=C.a(c,D),C.t(c));return new a(b[0],b[1],b[2])}
function da(a){var b=a.id;if(b==x)if(E!==x)E={A:"Multiple anonymous defines in url"};else if(!(b=C.W()))E=a;if(b!=x){var c=F[b];b in F||(c=C.j(b,D).a,c=F[b]=C.v(c,b));if(!(c instanceof w))throw Error("duplicate define: "+b);c.ba=k;C.w(c,a)}}
var D,I,J,K=l.document,L=K&&(K.head||K.getElementsByTagName("head")[0]),ea=L&&L.getElementsByTagName("base")[0]||null,fa={},ga={},M={},ha="addEventListener"in l?{}:{loaded:1,complete:1},v={},aa=v.toString,x,F={},N=k,E,ia=/\?/,ja=/^\/|^[^:]+:\/\//,ba=/(\.)(\.?)(?:$|\/([^\.\/]+.*)?)/g,ka=/\/\*[\s\S]*?\*\/|(?:[^\\])\/\/.*?[\n\r]/g,la=/require\s*\(\s*["']([^"']+)["']\s*\)|(?:[^\\]?)(["'])/g,O,C;
C={K:function(a,b){return C.m(s(a,b))},m:function(a,b){return b.c&&a in b.c&&b.c[a].Z||a},n:function(a,b){a&&(b.G&&0>a.indexOf("/"))&&(a=q(b.G)+"/"+a);return a},f:function(a,b,c,e){function d(b){return C.m(s(b,g.id),a)}function f(b,c,f){var j,y;j=c&&function(a){c.apply(x,a)};if(p(b,"String")){b=d(b);f=F[b];y=f instanceof w&&f.b;if(!(b in F))throw Error("Module not resolved: "+b);if(j)throw Error("require(id, callback) not allowed");return y||f}z(C.h(C.f(a,g.id,b,e)),j,f)}var g;g=new w;g.id=b||"";
g.X=e;g.z=c;g.a=a;g.q=f;f.toUrl=function(b){return C.j(d(b),a).url};g.K=d;return g},v:function(a,b,c){var e,d,f;e=C.f(a,b,x,c);d=e.g;f=A(1,function(a){e.l=a;try{return C.P(e)}catch(b){e.d(b)}});e.g=function(a){z(c||N,function(){d(F[e.id]=f(a))})};e.B=function(a){z(c||N,function(){e.b&&(f(a),e.p(ga))})};return e},M:function(a,b,c,e){return C.f(a,c,x,e)},V:function(a){return a.q},C:function(a){return a.b||(a.b={})},U:function(a){var b=a.o;b||(b=a.o={id:a.id,uri:C.D(a),exports:C.C(a),config:function(){return a.a}},
b.b=b.exports);return b},D:function(a){return a.url||(a.url=C.u(a.q.toUrl(a.id)),a.a)},a:function(a){var b,c,e,d,f,g;b=!a;a&&(C.a=C.F);a||(a={});e=a.apiName||"curl";d=a.apiContext||l;f=a.defineName||"define";g=a.defineContext||l;c=a.overwriteApi;!b&&I&&(l.curl=I,I=k);if(!b&&!c&&d[e]&&d[e]!=B)throw Error(e+" already exists");d[e]=B;if(!b||!l.define){if(!b&&!c&&f in g&&g[f]!=J)throw Error(f+" already exists");g[f]=J=function(){var a=C.T(arguments);da(a)};J.amd={plugins:h,jQuery:h,curl:"0.7.0"}}return C.F(a)},
F:function(a,b){function c(a,b){var e,c,g,i,G;for(G in a){g=a[G];g.name=g.id||g.name||G;i=d;c=ca(q(g.name||G));e=c.I;if(c=C.n(c.i,d))i=f[c],i||(i=f[c]=u(d),i.c=u(d.c),i.e=[]),delete a[G];if(b){c=g;var H=void 0;c.path=q(c.path||c.location||"");H=q(c.main)||"main";"."!=H.charAt(0)&&(H="./"+H);c.Z=s(H,c.name+"/");c.a=c.config;c.a&&(c.a=u(d,c.a))}else c={path:q(g)};c.J=e.split("/").length;e?(i.c[e]=c,i.e.push(e)):i.s=C.H(g,d)}}function e(a){var b=a.c;a.$=RegExp("^("+a.e.sort(function(a,c){return b[c].J-
b[a].J}).join("|").replace(/\/|\./g,"\\$&")+")(?=\\/|$)");delete a.e}var d,f,g;b||(b={});d=u(b,a);d.s=d.baseUrl||"";d.G=d.pluginPath||"curl/plugin";d.N=RegExp(d.dontAddFileExt||ia);d.c=u(b.c);f=a.plugins||{};d.plugins=u(b.plugins);for(g in f)d.plugins[C.n(g,d)]=f[g];f=d.plugins;d.e=[];c(a.paths,k);c(a.packages,h);for(g in f){f[g]=u(d,f[g]);var i=f[g].e;i&&(f[g].e=i.concat(d.e),e(f[g]))}e(d);return d},t:function(a){var b;(b=a&&a.preloads)&&0<b.length&&z(N,function(){N=C.h(C.f(D,x,b,h))})},j:function(a,
b){var c,e,d,f;c=b.c;d=ja.test(a)?a:a.replace(b.$,function(a){e=c[a]||{};f=e.a;return e.path||""});return{a:f||D,url:C.H(d,b)}},H:function(a,b){var c=b.s;return c&&!ja.test(a)?q(c)+"/"+a:a},u:function(a,b){return a+((b||D).N.test(a)?"":".js")},Y:function(a,b,c){var e=K.createElement("script");e.onload=e.onreadystatechange=function(c){c=c||l.event;if("load"==c.type||ha[e.readyState])delete M[a.id],e.onload=e.onreadystatechange=e.onerror="",b()};e.onerror=function(){c(Error("Syntax or http error: "+
a.url))};e.type=a.ca||"text/javascript";e.charset="utf-8";e.async=!a.da;e.src=a.url;M[a.id]=e;L.insertBefore(e,ea);return e},Q:function(a){var b=[],c;("string"==typeof a?a:a.toSource?a.toSource():a.toString()).replace(ka,"").replace(la,function(a,d,f){f?c=c==f?x:c:c||b.push(d);return""});return b},T:function(a){var b,c,e,d,f,g;f=a.length;e=a[f-1];d=p(e,"Function")?e.length:-1;2==f?p(a[0],"Array")?c=a[0]:b=a[0]:3==f&&(b=a[0],c=a[1]);!c&&0<d&&(g=h,c=["require","exports","module"].slice(0,d).concat(C.Q(e)));
return{id:b,l:c||[],r:0<=d?e:function(){return e},k:g}},P:function(a){var b;b=a.r.apply(a.k?a.b:x,a.l);b===x&&a.b&&(b=a.o?a.b=a.o.b:a.b);return b},w:function(a,b){a.r=b.r;a.k=b.k;a.z=b.l;C.h(a)},h:function(a){function b(a,b,c){g[b]=a;c&&m(a,b)}function c(b,c){var e,d,f,g;e=A(1,function(a){d(a);j(a,c)});d=A(1,function(a){m(a,c)});f=C.R(b,a);(g=f instanceof w&&f.b)&&d(g);z(f,e,a.d,a.b&&function(a){f.b&&(a==fa?d(f.b):a==ga&&e(f.b))})}function e(){a.g(g)}var d,f,g,i,r,m,j;g=[];f=a.z;i=f.length;0==f.length&&
e();m=A(i,b,function(){a.B&&a.B(g)});j=A(i,b,e);for(d=0;d<i;d++)r=f[d],r in O?(j(O[r](a),d,h),a.b&&a.p(fa)):r?c(r,d):j(x,d,h);return a},S:function(a){C.D(a);C.Y(a,function(){var b=E;E=x;a.ba!==k&&(!b||b.A?a.d(Error(b&&b.A||"define() missing or duplicated: "+a.url)):C.w(a,b))},a.d);return a},R:function(a,b){var c,e,d,f,g,i,r,m,j,y;c=b.K;e=b.X;j=b.a||D;d=ca(a);i=d.I;f=d.i?C.m(C.n(s(d.i,b.id),j),j):c(i);r=C.j(f,j);if(d.i)g=f;else if(g=r.a.moduleLoader)i=f,f=g,r=C.j(g,j);d=F[f];f in F||(d=F[f]=C.v(r.a,
f,e),d.url=C.u(r.url,d.a),C.S(d));f==g&&(m=new w,y=j.plugins[g]||j,z(d,function(a){var b,d,f;f=a.dynamic;i="normalize"in a?a.normalize(i,c,y)||"":c(i);d=g+"!"+i;b=F[d];if(!(d in F)){b=C.M(y,d,i,e);f||(F[d]=b);var j=function(a){b.g(a);f||(F[d]=a)};j.resolve=j;j.reject=j.error=b.d;a.load(i,b.q,j,y)}m!=b&&z(b,m.g,m.d,m.p)},m.d));return m||d},W:function(){var a;if(!p(l.opera,"Opera"))for(var b in M)if("interactive"==M[b].readyState){a=b;break}return a}};O={require:C.V,exports:C.C,module:C.U};
B.version="0.7.0";D=l.curl;"function"==typeof D?(I=D,D=k):l.curl=x;D=C.a(D);C.t(D);F.curl=B;F["curl/_privileged"]={core:C,cache:F,config:function(){return D},_define:da,_curl:B,Promise:w};var P=this.document;function ma(){if(!P.body)return k;Q||(Q=P.createTextNode(""));try{return P.body.removeChild(P.body.appendChild(Q)),Q=na,h}catch(a){return k}}function R(){var a;a=oa[P[S]]&&ma();if(!T&&a){T=h;for(clearTimeout(U);pa=qa.pop();)pa();ra&&(P[S]="complete");for(var b;b=sa.shift();)b()}return a}
function ta(){R();T||(U=setTimeout(ta,ua))}var S="readyState",oa={loaded:1,interactive:1,complete:1},sa=[],ra=P&&"string"!=typeof P[S],T=k,ua=10,V,pa,qa=[],U,na,Q;V="addEventListener"in this?function(a,b){a.addEventListener(b,R,k);return function(){a.removeEventListener(b,R,k)}}:function(a,b){a.attachEvent("on"+b,R);return function(){a.detachEvent(b,R)}};P&&!R()&&(qa=[V(this,"load"),V(P,"readystatechange"),V(this,"DOMContentLoaded")],U=setTimeout(ta,ua));
define("curl/domReady",function(){function a(a){T?a():sa.push(a)}a.then=a;a.amd=h;return a});define("curl/plugin/domReady",["../domReady"],function(a){return{load:function(b,c,e){a(e)}}});
define("curl/plugin/text",function(){function a(){if("undefined"!==typeof XMLHttpRequest)a=function(){return new XMLHttpRequest};else for(var b=a=function(){throw Error("getXhr(): XMLHttpRequest not available");};0<c.length&&a===b;)(function(b){try{new ActiveXObject(b),a=function(){return new ActiveXObject(b)}}catch(c){}})(c.shift());return a()}function b(a){throw a;}var c=["Msxml2.XMLHTTP","Microsoft.XMLHTTP","Msxml2.XMLHTTP.4.0"];return{load:function(c,d,f){var c=d.toUrl(c),g=f.error||b,i=a();i.open("GET",
c,h);i.onreadystatechange=function(){4===i.readyState&&(400>i.status?f(i.responseText):g(Error("fetchText() failed. status: "+i.statusText)))};i.send(null)},"plugin-builder":"./builder/text"}});function va(){var a;a=W[wa]("link");a.rel="stylesheet";a.type="text/css";return a}function xa(a,b,c){ya.push({url:a,L:b,O:function(){c(Error(za))}});a=Aa.shift();!a&&Ba.length<Ca&&(a=W.createElement("style"),Ba.push(a),X.appendChild(a));a&&Y(a)}
function Y(a){var b;(b=ya.shift())?(a.onload=function(){b.L();Y(a)},a.onerror=function(){b.O();Y(a)},a.styleSheet.addImport(b.url)):(a.onload=a.onerror=Z,Aa.push(a))}function Da(a,b,c){if(!$.load){var e;var d,f;if(!a.href||W.readyState&&"complete"!=W.readyState)e=k;else{e=k;try{if(d=a.sheet)f=d.cssRules,e=null===f,!e&&"length"in f&&(d.insertRule("-curl-css-test {}",0),d.deleteRule(0),e=h)}catch(g){e=/security|denied/i.test(g.message)}}e?c():a.onload==Z||!a.onload||Ea(function(){Da(a,b,c)},b)}}
function Fa(a,b,c,e){function d(){if(f.onload!=Z&&f.onload){f.onload=f.onerror=Z;var a=function(){!W.readyState||"complete"==W.readyState?b():Ea(a,10)};a()}}var f;f=va();f.onload=function(){$.load=$.load||h;d()};Da(f,e,d);f.onerror=function(){$.error=$.error||h;f.onload!=Z&&f.onload&&(f.onload=f.onerror=Z,c(Error(za)))};f.href=a;X.appendChild(f)}function Z(){}
var wa="createElement",Ea=this.setTimeout,W=this.document,X,Ga=W&&W.createStyleSheet&&!(10<=W.documentMode),Ba=[],Aa=[],ya=[],Ca=12,Ha,za="HTTP or network error.",$={};W&&(X=W.head||W.getElementsByTagName("head")[0],Ha=Ga?xa:Fa);
define("curl/plugin/css",{normalize:function(a,b){var c,e;if(!a)return a;c=a.split(",");e=[];for(var d=0,f=c.length;d<f;d++)e.push(b(c[d]));return e.join(",")},load:function(a,b,c,e){function d(){0==--r&&c()}function f(a){(c.d||function(a){throw a;})(a)}var g,i,r,m;g=(a||"").split(",");i=e.cssWatchPeriod||50;e=e.cssNoWait;r=g.length;for(m=0;m<g.length;m++){var a=g[m],j,a=b.toUrl(a.lastIndexOf(".")<=a.lastIndexOf("/")?a+".css":a);e?(j=va(),j.href=a,X.appendChild(j),d()):Ha(a,d,f,i)}},"plugin-builder":"./builder/css",
pluginBuilder:"./builder/css"});
}).call(this);
